config/routes.rb
Concertapp::Application.routes.draw do

  

  devise_for :users
  resources :events
  
  resources :friendships
  

  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date , :time , :artist , :price , :description , :sc_url , :user_name , :user_id , :picture
  belongs_to :user
  has_attached_file :picture, :styles => { :medium => "150x150>", :thumb => "80x80>" }
  validates :artist, :description, :presence => true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
   belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:user_name , :id
  has_many :events
  
  has_many :friendships
  has_many :friends, :through => :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_filter  :only => [:new, :create, :destroy , :edit , :update]
  def index

         
        @events = Event.order(:date).page(params[:page]).per(6)
       
        respond_to do |format|
            format.html  # index.html.erb
            format.json  { render :json => @events }
        end
    end

    def new
        @event = Event.new
 
        respond_to do |format|
            format.html  # new.html.erb
            format.json  { render :json => @event }
        end
    end

    def create
         @event = Event.new(params[:event])

        respond_to do |format|
            if @event.save
                format.html  { redirect_to(@event,
                        :notice => 'The event was successfully created.') }
                format.json  { render :json => @event,
                        :status => :created, :location => @event }
            else
                format.html  { render :action => "new" }
                format.json  { render :json => @event.errors,
                    :status => :unprocessable_entity }
            end
        end
    end

    def show
        @event = Event.find(params[:id])
        respond_to do |format|
            format.html   
            format.json  { render :json => @event }
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

      def update
        @event = Event.find(params[:id])
        
         respond_to do |format|
           if @event.update_attributes(params[:event])
             format.html  { redirect_to(@event,
                           :notice => 'The event was successfully updated.') }
             format.json  { head :no_content }
           else
             format.html  { render :action => "edit" }
             format.json  { render :json => @event.errors,
                           :status => :unprocessable_entity }
           end
         end
      end

      def destroy
        @event = Event.find(params[:id])
        @event.destroy
        
         respond_to do |format|
           format.html { redirect_to events_url }
           format.json { head :no_content }
         end
      end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
def index
  @friendships = Friendship.all
end

def create
  @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  if @friendship.save
    flash[:notice] = "Added friend."
    redirect_to root_url
  else
    flash[:notice] = "Unable to add friend."
    redirect_to root_url
  end
end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
  @friendship.destroy
  flash[:notice] = "Removed friendship."
  redirect_to current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_follow.html.erb
<%= link_to "follow", friendships_path(:friend_id => user), :method => :post %>

app/views/events/_form.html.erb
<%= simple_form_for(@event, html: {class: "form-horizontal"} , html: {:multipart => true } ) do |f| %>
  <% if @event.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited
        this song from being saved:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%=f.hidden_field :user_id, :value => current_user.id %>
 
    <%= f.input :artist ,:label => 'Event name / Artist' %>
    <%= f.input :time ,:label => 'time?' %>
   
    <%= f.input :date, :input_html => { :id => 'datepicker'} %>
    <%= f.input :price ,:label => 'How much $$$?' %>
    <%= f.input :description, :label => 'What?' , :input_html => { :class => 'text_area_custom' } %>
    <%= f.input :artist_name, :label => 'Artist' , :input_html => { :id => 'artist_name' } %>
    <%= f.input :sc_url, collection: [@event.sc_url], :prompt => "Select the track", input_html: { style: 'width: 100%' , :id => 'sc_url'}   %>
    
    <%= f.file_field :picture %>
 
   
    </script>
  </br>
  
    <%= f.button :submit %>
  
<% end %>

app/views/events/_scplayer.html.erb
<% require "soundcloud" %>
<% client = Soundcloud.new(client_id: 'c424d31d2d5919a0f378269cc39b60a7') %>
<% embed_info = client.get('/oembed', url: @event.sc_url) %>

<%= embed_info['html'].html_safe %>

app/views/events/create.html.erb
<h1>Create new event</h1>
<p>Schedule a new event</p>

<%= render 'form' %>
 
<%= link_to 'Back', events_path %>

app/views/events/edit.html.erb
<h1>Events edit</h1>
 

<%= render 'form' %>
 
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Available Events/Concerts</h1>


 <%=paginate @events%>
  <table class = "table table-hover">
      <br>
       <% if user_signed_in? %>
        <%= link_to 'add new event', new_event_path %>
        <% end %>
     </div>
     <tr>
       <th>By:</th>
       <th>Event</th>
       <th>Time</th>
       <th>Date</th>
       <th>Price</th>
       <th>Description</th>
       <th>Details</th>
       <th>Edit</th>
       <th>Destroy</th>
     </tr>




      
   <% @events.each do |event| %>
     <tr>
      <td><%= event.user.user_name %><br> <%= link_to "follow", friendships_path(:friend_id => event.user), :method => :post %></td>
       <td><%= event.artist  %><%= image_tag event.picture.url(:thumb) %></td>
       <td><%= event.time %></td>
       <td><%= event.date %></td>
       <td><%= event.price  %></td>
       <td><%= event.description  %></td>
      <% if user_signed_in? %>
        <td><%= link_to 'Details', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?',:method => :delete %></td>
      <% else %>
        <td></td>
        <td></td>
        <td></td>
      <% end %>
     </tr>
   <% end %>
   </table>


 

app/views/events/new.html.erb
 
<h1>Create new event</h1>
<p>Schedule a new event</p>

<%= render 'form' %>
 
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Details</h1>
<p id="notice"><%= notice %></p>


<%= render 'scplayer' %>
</br>
</br>


<%= image_tag @event.picture.url(:medium) %>
<p>
  <b>Artist:</b>
  <%= @event.artist %>
</p>
 </br>
<p>
  <b>Time of the event:</b>
  <%= @event.time %>
</p>
  </br>
<p>
  <b>Date of the event:</b>
  <%= @event.date %>
</p>
 </br>
<p>
  <b>Price:</b>
  <%= @event.price %>
</p>
 
 

</br>
<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/trusted.html.erb
<% user= User.find(@event.user_id)%>
<h1> my profile <h1>
 
<p>Username: <%= user.user_name%></p>
 
<h2>Your Friends</h2>
<ul>
  <% for user in user.friends %>
  <li><%=  user.user_name %></li>
  <% end %>  
</ul>

<%= link_to 'Back', events_path %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/friendships/show.html.erb
<% user= User.find(@event.user_id)%>
<h1> my profile <h1>
 
<p>Username: <%= user.user_name%></p>
 
<h2>Your Friends</h2>
<ul>
  <% for user in user.friends %>
  <li><%=  user.user_name %></li>
  <% end %>  
</ul>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concertapp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
  <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
  <script src="http://connect.soundcloud.com/sdk.js"></script>
     <script>
        SC.initialize({
          client_id: "c424d31d2d5919a0f378269cc39b60a7"
        });
      </script>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Concerts & Performances</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="#about">About</a></li>
                 
                 <ul class = "nav pull-right">
                  <% if user_signed_in? %>
                      <li><%= link_to current_user.email, edit_user_registration_path %></li>
                      <li><%= link_to 'Trusted', friendships_path, method: :get %></a></li>
                      <li><%= link_to "Log out" ,destroy_user_session_path, method: :delete %></li>
                  <% else %>
                      <li><%= link_to "Sign up", new_user_registration_path %></li>
                      
                      <li><%= link_to "Log in", new_user_session_path %></li>
                  <% end %>
                  </ul>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>


<div class="container">
</br>
  <div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item"><% image_tag("img1.jpg") %><img src="assets/img1.jpg" alt="Icon"></div> 
      <div class="item"><% image_tag("img1.jpg") %><img src="assets/img1.jpg" alt="Icon"></div> 
      <div class="item"><% image_tag("img2.jpg") %><img src="assets/img2.jpg" alt="Icon"></div>
      <div class="item"><% image_tag("img3.jpg") %><img src="assets/img3.jpg" alt="Icon"></div>
      <div class="item"><% image_tag("img4.jpg") %><img src="assets/img4.jpg" alt="Icon"></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>



        <% flash.each do |type, message| %>
            <div class = "alert <%= flash_class type %>" >
                <button class="close" data-dismiss = "alert" >x</button> 
              <%= message %>
            </div>
            <% end %>
      <%= yield %>
    </div>


</body>
</html>